import { useState } from "react";
import clsx from "clsx";
import Link from "@docusaurus/Link";
import useBaseUrl from "@docusaurus/useBaseUrl";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import Layout from "@theme/Layout";

import Heading from "@theme/Heading";
import styles from "./index.module.css";

const textContent = {
  customTests: `
  Write Pester tests that encode your organization's business and security policies.<br/><br/>
  <strong>Apply modern DevSecOps practices</strong> and continuously monitor critical aspects of your Microsoft cloud.
  `,
  whatIf: `
  Avoid creating loopholes in your conditional access policies and test to see the impact of a policy change before it is applied.<br/><br/>

  <strong>Identity is the new control plane!</strong> Create iron-clad tests to ensure your tenant's posture is always secure as your access policies evolve.
  `,
  m365advisorArchitecture: `
  M365 Advisor is built on top of Pester, the PowerShell test framework and <strong>super charges</strong> it with cloud capabilities and user friendly reports.<br/><br/>
  Quickly set up M365 Advisor in your environment by following the step-by-step guides we've built for you.<br/><br/>
  Bring the ease of writing tests in PowerShell to your Microsoft 365 tenant with M365 Advisor!<br/><br/>
  `,
  m365advisorReport: `
Get a quick snapshot of your tenant's security posture with the report generated by M365 Advisor.<br/><br/>
<strong>The interactive click-through</strong> report lets you drill down to the details of
each test.
<br/><br/>`,
  quickFix: `
Test details include direct links to the Microsoft admin portals.<br/><br/>
<strong>Jump straight</strong> into the conditional access policy that needs to be fixed or the group that needs to be reviewed.
<br/><br/>`,
  eidsca: `
M365 Advisor includes over 40+ out of the box tests from <a href="/docs/tests/eidsca/">Entra ID Security Config Analyzer (EIDSCA).</a><br/><br/>
EIDSCA is a part of the <strong>Microsoft Entra ID - Attack and Defense Playbook</strong> and is a collection of common attack scenarios on Microsoft Entra ID and how they can be mitigated.
<br/><br/>`,
  emailAlert: `
Set up email alerts to be delivered to your inbox with a
summary of the test results.
<br/><br/>
<strong>Get notified</strong> when a change is introduced in your Microsoft 365 tenant
that affects the security configuration.`,
  azureDevOps: `
M365 Advisor can be integrated with Azure DevOps Pipelines and scheduled to be run daily
and when changes are introduced in your Microsoft 365 tenant.
<br/><br/>
<strong>Follow the step-by-step guide</strong> in the M365 Advisor docs to set up
an automation account with Workload Identify Federation.`,
  gitHub: `
Integrate M365 Advisor with GitHub Actions to continuously monitor your tenant configuration.
<br/><br/>
<strong>Build an archive history</strong> of M365 Advisor test runs against your tenant with the native
workflow integration in M365 Advisor.
<br/><br/>
<strong>Use Workload Identify Federation</strong> for your automation account to connect to Microsoft Graph (no more secrets or credential rotation!).`,
};

const stats = [
  { value: "500K+", label: "PowerShell Gallery downloads" },
  { value: "120K+", label: "Tenants protected" },
  { value: "360+", label: "Built-in security tests" },
  { value: "5", label: "Compliance frameworks" },
];

const features = [
  {
    icon: "🔥",
    title: "Ready-made tests",
    body: "Hundreds of curated tests covering identity, access, devices and apps — ready to run on day one.",
  },
  {
    icon: "🛡️",
    title: "Confidently make changes",
    body: "Run regression tests before you change a Conditional Access policy. Catch loopholes before attackers do.",
  },
  {
    icon: "🛰️",
    title: "Continuous monitoring",
    body: "Schedule M365 Advisor in GitHub Actions, Azure DevOps or Azure Automation. Get alerts when posture drifts.",
  },
  {
    icon: "🧩",
    title: "Easy to customize",
    body: "Built on Pester and Microsoft Graph. Encode your own business and security policies as code.",
  },
  {
    icon: "🧭",
    title: "Configuration guidance",
    body: "Every test ships with remediation steps and direct links into the Microsoft admin portals.",
  },
  {
    icon: "🦅",
    title: "Compliance baselines",
    body: "EIDSCA, CISA SCuBA, CIS Microsoft 365 and ORCA — all wired into a single test framework.",
  },
];

const suites = [
  {
    emoji: "🔥",
    title: "M365 Advisor",
    desc: "Best-practice tests curated by the M365 Advisor community.",
    count: "170+ tests",
    href: "/docs/tests/m365advisor",
  },
  {
    emoji: "🛡️",
    title: "EIDSCA",
    desc: "Entra ID Security Config Analyzer baseline.",
    count: "60+ tests",
    href: "/docs/tests/eidsca",
  },
  {
    emoji: "🦅",
    title: "CISA SCuBA",
    desc: "US CISA Secure Cloud Business Applications baselines.",
    count: "70+ tests",
    href: "/docs/tests/cisa",
  },
  {
    emoji: "🌀",
    title: "CIS M365",
    desc: "CIS Microsoft 365 Foundations Benchmark v3.1.0.",
    count: "60+ tests",
    href: "/docs/tests/cis",
  },
  {
    emoji: "📨",
    title: "ORCA",
    desc: "Office 365 Recommended Configuration Analyzer.",
    count: "Exchange Online",
    href: "/docs/tests/orca",
  },
];

function Hero() {
  const { siteConfig } = useDocusaurusContext();
  const logoUrl = useBaseUrl("/img/logo.svg");
  return (
    <header className={styles.hero}>
      <div className={styles.heroGlow} aria-hidden="true" />
      <div className="container">
        <div className={styles.heroInner}>
          <span className={styles.heroBadge}>
            <span className={styles.heroBadgeDot} aria-hidden="true" />
            Open source · Community driven
          </span>
          <div className={styles.heroLogoWrap}>
            <img className={styles.heroLogo} src={logoUrl} alt="M365 Advisor" />
          </div>
          <Heading as="h1" className={styles.heroTitle}>
            Test automation for your <em>Microsoft 365</em> security posture
          </Heading>
          <p className={styles.heroSubtitle}>
            {siteConfig.tagline} — M365 Advisor turns Microsoft security best
            practices into runnable tests so you can make changes with
            confidence and prove compliance over time.
          </p>
          <div className={styles.heroButtons}>
            <Link className={styles.btnPrimary} to="/docs/installation">
              Get Started →
            </Link>
            <Link
              className={styles.btnGhost}
              to="https://github.com/m365advisor365/m365advisor"
            >
              Star on GitHub
            </Link>
          </div>
        </div>
        <div className={styles.heroShowcase}>
          <div className={styles.heroShowcaseFrame}>
            <img
              className={styles.heroShowcaseMedia}
              src={useBaseUrl("/img/m365advisor-demo.gif")}
              alt="M365 Advisor running in a terminal and producing an interactive HTML report"
              loading="lazy"
            />
          </div>
        </div>
      </div>
    </header>
  );
}

function Stats() {
  return (
    <section className={styles.statsSection}>
      <div className="container">
        <div className={styles.stats}>
          {stats.map((s) => (
            <div key={s.label} className={styles.statItem}>
              <span className={styles.statValue}>{s.value}</span>
              <span className={styles.statLabel}>{s.label}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Features() {
  return (
    <section className={clsx(styles.section, styles.sectionAtmosphere)}>
      <div className="container">
        <div className={styles.sectionHeader}>
          <span className={styles.eyebrow}>Why M365 Advisor</span>
          <Heading as="h2" className={styles.sectionTitle}>
            Security as code, for the Microsoft cloud
          </Heading>
          <p className={styles.sectionLede}>
            One framework, hundreds of tests, every change validated. M365 Advisor
            is how modern teams keep Microsoft 365 secure as it evolves.
          </p>
        </div>
        <div className={styles.featureGrid}>
          {features.map((f) => (
            <article key={f.title} className={styles.featureCard}>
              <div className={styles.featureIcon} aria-hidden="true">
                {f.icon}
              </div>
              <h3 className={styles.featureTitle}>{f.title}</h3>
              <p className={styles.featureBody}>{f.body}</p>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}

function Suites() {
  return (
    <section className={styles.section}>
      <div className="container">
        <div className={styles.sectionHeader}>
          <span className={styles.eyebrow}>Test suites</span>
          <Heading as="h2" className={styles.sectionTitle}>
            Five baselines, one report
          </Heading>
          <p className={styles.sectionLede}>
            Run the suites you care about — community best practices and the
            major Microsoft 365 compliance baselines, all in one place.
          </p>
        </div>
        <div className={styles.suitesGrid}>
          {suites.map((s) => (
            <Link key={s.title} className={styles.suiteCard} to={s.href}>
              <span className={styles.suiteEmoji} aria-hidden="true">
                {s.emoji}
              </span>
              <h3 className={styles.suiteTitle}>{s.title}</h3>
              <p className={styles.suiteDesc}>{s.desc}</p>
              <span className={styles.suiteCount}>{s.count}</span>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}

function CtaBand() {
  return (
    <section>
      <div className="container">
        <div className={styles.ctaBand}>
          <Heading as="h2" className={styles.ctaTitle}>
            Run your first M365 Advisor test in under a minute
          </Heading>
          <p className={styles.ctaSubtitle}>
            Install the PowerShell module, connect to Microsoft Graph and get
            an interactive HTML report of your tenant's posture.
          </p>
          <div className={styles.heroButtons}>
            <Link className={styles.btnPrimary} to="/docs/installation">
              Get Started →
            </Link>
            <Link
              className={styles.btnGhost}
              to="https://github.com/m365advisor365/m365advisor"
            >
              View on GitHub
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ---------- Existing product story sections (kept) ---------- */

export function Section({
  element = "section",
  children,
  className,
  background = "light",
}) {
  const El = element;
  return (
    <El
      className={
        className
          ? `Section ${className} ${background}`
          : `Section ${background}`
      }
    >
      {children}
    </El>
  );
}

function Heading2({ text }) {
  return <h2 className="Heading">{text}</h2>;
}

function TextColumn({ title, text, moreContent }) {
  return (
    <div className="RightText">
      <Heading2 text={title} />
      <div dangerouslySetInnerHTML={{ __html: text }} />
      {moreContent}
    </div>
  );
}

function TwoColumns({ columnOne, columnTwo, reverse }) {
  return (
    <div className={`TwoColumns ${reverse ? "reverse" : ""}`}>
      <div className={`column first ${reverse ? "right" : "left"}`}>
        {columnOne}
      </div>
      <div className={`column last ${reverse ? "left" : "right"}`}>
        {columnTwo}
      </div>
    </div>
  );
}

function CustomTests() {
  return (
    <Section className="CrossPlatform" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn
            title="Security as Code (SaC)"
            text={textContent.customTests}
          />
        }
        columnTwo={
          <img
            className="FeatureImageLeft"
            alt="Code snippet for a custom test"
            src="img/home/custom-test.png"
          />
        }
      />
    </Section>
  );
}

function WhatIf() {
  return (
    <Section className="CrossPlatform">
      <TwoColumns
        columnOne={
          <TextColumn
            title="Conditional Access What-If"
            text={textContent.whatIf}
          />
        }
        columnTwo={
          <img
            className="FeatureImageRight"
            alt="Code sample of a what if test"
            src="img/home/conditional-access-policywhat-if-test.png"
          />
        }
      />
    </Section>
  );
}

function M365AdvisorArchitecture() {
  return (
    <Section className="CrossPlatform" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn
            title="M365 Advisor Test Framework"
            text={textContent.m365advisorArchitecture}
          />
        }
        columnTwo={
          <img
            className="FeatureImageLeft"
            alt="Architecture diagram of M365 Advisor test framework"
            src="img/home/m365advisor-architecture.png"
          />
        }
      />
    </Section>
  );
}

function M365AdvisorReport() {
  return (
    <Section className="CrossPlatform">
      <TwoColumns
        columnOne={
          <TextColumn
            title="🔥 M365 Advisor Test Reports"
            text={textContent.m365advisorReport}
          />
        }
        columnTwo={
          <img
            className="FeatureImageRight"
            alt="M365 Advisor summary report"
            src="img/home/m365advisor-report.png"
          />
        }
      />
    </Section>
  );
}

function GitHubSection() {
  return (
    <Section className="CrossPlatform LeftImage" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn title="M365 Advisor ❤️ GitHub" text={textContent.gitHub} />
        }
        columnTwo={
          <img
            className="FeatureImageLeft"
            alt="GitHub reports"
            src="img/home/github-m365advisor-report.png"
          />
        }
      />
    </Section>
  );
}

function AzureDevOps() {
  return (
    <Section className="CrossPlatform">
      <TwoColumns
        columnOne={
          <TextColumn
            title="M365 Advisor 💛 Azure DevOps"
            text={textContent.azureDevOps}
          />
        }
        columnTwo={
          <img
            className="FeatureImageRight"
            alt="Azure DevOps Screenshot"
            src="img/home/azure-devops-m365advisor-report.png"
          />
        }
      />
    </Section>
  );
}

function EmailAlert() {
  return (
    <Section className="CrossPlatform" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn title="Email Alerts" text={textContent.emailAlert} />
        }
        columnTwo={
          <img
            className="FeatureImageLeft"
            alt="Outlook email alerts"
            src="img/home/email-alert-test-results.png"
          />
        }
      />
    </Section>
  );
}

function Eidsca() {
  return (
    <Section className="CrossPlatform">
      <TwoColumns
        columnOne={
          <TextColumn title="40+ EIDSCA Tests" text={textContent.eidsca} />
        }
        columnTwo={
          <img
            className="FeatureImageRight"
            alt="Screenshot of an EIDSCA test result"
            src="img/home/m365advisor-report-eidsca.png"
          />
        }
      />
    </Section>
  );
}

function QuickRemediation() {
  return (
    <Section className="CrossPlatform" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn title="Quick remediation" text={textContent.quickFix} />
        }
        columnTwo={
          <img
            alt="Screenshot of an EIDSCA test result"
            src="img/home/m365advisor-report-detail.png"
          />
        }
      />
    </Section>
  );
}

function UnifiedHero() {
  const { siteConfig } = useDocusaurusContext();
  const logoUrl = useBaseUrl("/img/logo.svg");

  return (
    <header className={styles.unifiedHero}>
      <div className={styles.gridBackground} style={{ position: 'absolute', inset: 0, zIndex: 0 }} />
      <div className={styles.heroGlow} aria-hidden="true" style={{ opacity: 0.7 }} />
      <div className="container" style={{ position: 'relative', zIndex: 1 }}>
        <div className={styles.heroInner}>
          <Heading as="h1" className={styles.unifiedTitle}>
            Unified Microsoft 365<br/>Compliance Advisor
          </Heading>
          <p className={styles.unifiedLede}>
            M365Advisor seamlessly integrates security baselines, identity audit tools, and compliance frameworks to keep your tenant secure.
          </p>
          <div className={styles.heroButtons}>
            <Link className={clsx(styles.btnPrimary, styles.primaryCta)} to="/get-started">
              Get Started Now →
            </Link>
          </div>
        </div>

        {/* Isometric Network Diagram */}
        <div className={styles.networkContainer}>
          <div className={styles.networkScene}>
            <div className={styles.networkGrid} />

            <svg className={styles.networkSvg} viewBox="0 0 800 400" width="800" height="400" preserveAspectRatio="none">
              {/* SVG Connecting paths */}
              <path id="path1" d="M 400 200 L 160 80" stroke="rgba(0, 242, 254, 0.15)" strokeWidth="1.5" fill="none" />
              <path id="path2" d="M 400 200 L 400 60" stroke="rgba(0, 242, 254, 0.15)" strokeWidth="1.5" fill="none" />
              <path id="path3" d="M 400 200 L 640 80" stroke="rgba(0, 242, 254, 0.15)" strokeWidth="1.5" fill="none" />
              <path id="path4" d="M 400 200 L 120 200" stroke="rgba(0, 242, 254, 0.15)" strokeWidth="1.5" fill="none" />
              <path id="path5" d="M 400 200 L 680 200" stroke="rgba(0, 242, 254, 0.15)" strokeWidth="1.5" fill="none" />
              <path id="path6" d="M 400 200 L 160 320" stroke="rgba(0, 242, 254, 0.15)" strokeWidth="1.5" fill="none" />
              <path id="path7" d="M 400 200 L 400 340" stroke="rgba(0, 242, 254, 0.15)" strokeWidth="1.5" fill="none" />
              <path id="path8" d="M 400 200 L 640 320" stroke="rgba(0, 242, 254, 0.15)" strokeWidth="1.5" fill="none" />

              {/* Animated glowing dots */}
              <circle r="4" fill="#00f2fe" filter="drop-shadow(0 0 4px #00f2fe)">
                <animateMotion dur="2.5s" repeatCount="indefinite" path="M 400 200 L 160 80" />
              </circle>
              <circle r="4" fill="#4facfe" filter="drop-shadow(0 0 4px #4facfe)">
                <animateMotion dur="3.2s" repeatCount="indefinite" path="M 400 200 L 400 60" />
              </circle>
              <circle r="4" fill="#00f2fe" filter="drop-shadow(0 0 4px #00f2fe)">
                <animateMotion dur="2.8s" repeatCount="indefinite" path="M 400 200 L 640 80" />
              </circle>
              <circle r="4" fill="#4facfe" filter="drop-shadow(0 0 4px #4facfe)">
                <animateMotion dur="3s" repeatCount="indefinite" path="M 400 200 L 120 200" />
              </circle>
              <circle r="4" fill="#00f2fe" filter="drop-shadow(0 0 4px #00f2fe)">
                <animateMotion dur="3.5s" repeatCount="indefinite" path="M 400 200 L 680 200" />
              </circle>
              <circle r="4" fill="#4facfe" filter="drop-shadow(0 0 4px #4facfe)">
                <animateMotion dur="2.7s" repeatCount="indefinite" path="M 400 200 L 160 320" />
              </circle>
              <circle r="4" fill="#00f2fe" filter="drop-shadow(0 0 4px #00f2fe)">
                <animateMotion dur="3.1s" repeatCount="indefinite" path="M 400 200 L 400 340" />
              </circle>
              <circle r="4" fill="#4facfe" filter="drop-shadow(0 0 4px #4facfe)">
                <animateMotion dur="2.9s" repeatCount="indefinite" path="M 400 200 L 640 320" />
              </circle>
            </svg>

            {/* Central floating glowing node */}
            <div className={styles.centralNode}>
              <img src={logoUrl} alt="M365 Advisor" />
            </div>

            {/* Isometric sub-nodes */}
            <div className={clsx(styles.subNode, styles.subNode1)}>🔐</div>
            <div className={clsx(styles.subNode, styles.subNode2)}>🛡️</div>
            <div className={clsx(styles.subNode, styles.subNode3)}>⚙️</div>
            <div className={clsx(styles.subNode, styles.subNode4)}>🌐</div>
            <div className={clsx(styles.subNode, styles.subNode5)}>📊</div>
            <div className={clsx(styles.subNode, styles.subNode6)}>🔍</div>
            <div className={clsx(styles.subNode, styles.subNode7)}>👁️</div>
            <div className={clsx(styles.subNode, styles.subNode8)}>🔑</div>
          </div>
        </div>
      </div>
    </header>
  );
}



function HowItWorks() {
  const [activeStep, setActiveStep] = useState(0); // Step 1 active by default

  const steps = [
    { id: 0, title: "Get Started", desc: "Click on 'Get Started' to navigate to the setup page and start your journey." },
    { id: 1, title: "Select Compliance Framework", desc: "Select the compliance framework (e.g. CIS, CISA SCuBA, EIDSCA) that matches your organization's security goals." },
    { id: 2, title: "Run Audit Commands", desc: "Run the generated PowerShell commands to initiate the compliance audit and display test results." },
  ];

  let activeCard = activeStep;

  return (
    <section className={styles.howItWorksSection} style={{ background: '#050608' }}>
      <div className="container">
        <div className={styles.howItWorksGrid}>
          {/* Steps list */}
          <div className={styles.workflowList}>
            <span className={styles.eyebrow} style={{ textAlign: 'left' }}>Execution Workflow</span>
            <h2 className={styles.howItWorksTitle} style={{ textAlign: 'left' }}>How it works</h2>
            <p className={styles.howItWorksSubtitle} style={{ textAlign: 'left' }}>
              Our structured process delivers end-to-end protection with precise automated test runs.
            </p>
            {steps.map((step) => (
              <div
                key={step.id}
                className={clsx(styles.workflowItem, activeStep === step.id && styles.workflowItemActive)}
                onMouseEnter={() => setActiveStep(step.id)}
                onClick={() => setActiveStep(step.id)}
              >
                <div className={styles.stepNumber}>0{step.id + 1}</div>
                <div className={styles.stepContent}>
                  <h3 className={styles.stepTitle}>{step.title}</h3>
                  <div className={styles.stepDesc}>{step.desc}</div>
                </div>
              </div>
            ))}
          </div>

          {/* 3D Graphic */}
          <div className={styles.layeredGraphic}>
            <div className={styles.layeredScene}>
              {/* Layer 01 */}
              <div className={clsx(styles.layerCard, styles.layerCard1, activeCard === 0 && styles.layerActive)}>
                <div className={styles.layerHeader}>
                  <span className={styles.layerTitle}>01 / Get Started</span>
                  <div className={styles.layerPills}>
                    <div className={clsx(styles.layerPill, activeCard === 0 && styles.layerPillActive)} />
                    <div className={styles.layerPill} />
                    <div className={styles.layerPill} />
                  </div>
                </div>
                <div className={styles.layerBody}>
                  <div className={styles.layerLine} style={{ width: '80%' }} />
                  <div className={styles.layerLine} style={{ width: '50%' }} />
                  <div className={styles.layerLine} style={{ width: '90%' }} />
                </div>
                <div style={{ color: activeCard === 0 ? '#00f2fe' : '#64748b', fontSize: '0.8rem', fontWeight: '500' }}>
                  Navigating to setup page...
                </div>
              </div>

              {/* Layer 02 */}
              <div className={clsx(styles.layerCard, styles.layerCard2, activeCard === 1 && styles.layerActive)}>
                <div className={styles.layerHeader}>
                  <span className={styles.layerTitle} style={{ color: activeCard === 1 ? '#00f2fe' : '#64748b' }}>02 / Select Framework</span>
                  <div className={styles.layerPills}>
                    <div className={styles.layerPill} />
                    <div className={clsx(styles.layerPill, activeCard === 1 && styles.layerPillActive)} />
                    <div className={styles.layerPill} />
                  </div>
                </div>
                <div className={styles.layerBody}>
                  <div className={styles.layerLine} style={{ width: '40%', background: activeCard === 1 ? '#00f2fe' : 'rgba(255,255,255,0.05)' }} />
                  <div className={styles.layerLine} style={{ width: '75%', background: activeCard === 1 ? '#4facfe' : 'rgba(255,255,255,0.05)' }} />
                  <div className={styles.layerLine} style={{ width: '60%' }} />
                </div>
                <div style={{ color: activeCard === 1 ? '#00f2fe' : '#64748b', fontSize: '0.8rem', fontWeight: '500' }}>
                  Choose CIS, CISA, EIDSCA...
                </div>
              </div>

              {/* Layer 03 */}
              <div className={clsx(styles.layerCard, styles.layerCard3, activeCard === 2 && styles.layerActive)}>
                <div className={styles.layerHeader}>
                  <span className={styles.layerTitle}>03 / Run Commands</span>
                  <div className={styles.layerPills}>
                    <div className={styles.layerPill} />
                    <div className={styles.layerPill} />
                    <div className={clsx(styles.layerPill, activeCard === 2 && styles.layerPillActive)} />
                  </div>
                </div>
                <div className={styles.layerBody}>
                  <div className={styles.layerLine} style={{ width: '90%' }} />
                  <div className={styles.layerLine} style={{ width: '85%' }} />
                  <div className={styles.layerLine} style={{ width: '40%' }} />
                </div>
                <div style={{ color: activeCard === 2 ? '#00f2fe' : '#64748b', fontSize: '0.8rem', fontWeight: '500' }}>
                  Executing PowerShell tests...
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function OurServices() {
  const assessments = [
    {
      id: "cis",
      title: "CIS Benchmarks",
      subtitle: "Foundations benchmark certification mapping",
      desc: "Over 44+ automated controls mapped to CIS Microsoft 365 Foundations Benchmark Levels 1 and 2 guidelines for defense-in-depth.",
      accent: "#fb923c", // Warm Orange
      glow: "rgba(251, 146, 60, 0.15)",
      icon: "🌀",
      count: "CIS L1/L2",
    },
    {
      id: "iso27001",
      title: "ISO/IEC 27001:2022",
      subtitle: "Information Security Management System",
      desc: "44 controls mapped to the international standard for information security (ISMS).",
      accent: "#059669", // Emerald Green
      glow: "rgba(5, 150, 105, 0.15)",
      icon: "🌐",
      count: "44 Controls",
    },
    {
      id: "iso27002",
      title: "ISO/IEC 27002:2022",
      subtitle: "Security Controls Guidance",
      desc: "44 controls mapped to ISO 27002 implementation guidelines for security controls.",
      accent: "#0d9488", // Teal
      glow: "rgba(13, 148, 136, 0.15)",
      icon: "📋",
      count: "44 Controls",
    },
    {
      id: "hippa",
      title: "HIPPA",
      subtitle: "Healthcare Security & Privacy Baseline",
      desc: "Automated controls mapping your tenant's security, privacy, and breach notification policies to HIPAA compliance rules.",
      accent: "#fb923c",
      glow: "rgba(251, 146, 60, 0.15)",
      icon: "🩺",
      count: "🔒 PREMIUM",
      isPremium: true,
      mailtoUrl: `mailto:Salman.Sayyed@onmeridian.com?subject=${encodeURIComponent("Access Request: Premium Module - HIPPA")}&body=${encodeURIComponent("Hi Salman,\n\nI want to access this premium HIPPA auditing module. Please provide me with the details on how to get started.\n\nThanks!")}`
    },
    {
      id: "rbi-nbfc",
      title: "RBI NBFC",
      subtitle: "RBI Master Directions for NBFCs",
      desc: "Checks validating IT governance, information security policy, cyber security controls, and vendor risk management.",
      accent: "#fb923c",
      glow: "rgba(251, 146, 60, 0.15)",
      icon: "🏦",
      count: "🔒 PREMIUM",
      isPremium: true,
      mailtoUrl: `mailto:Salman.Sayyed@onmeridian.com?subject=${encodeURIComponent("Access Request: Premium Module - RBI NBFC")}&body=${encodeURIComponent("Hi Salman,\n\nI want to access this premium RBI NBFC auditing module. Please provide me with the details on how to get started.\n\nThanks!")}`
    },
    {
      id: "dpdp",
      title: "DPDP Act 2023",
      subtitle: "Digital Personal Data Protection Act",
      desc: "Audit rules checking consent management systems, data principal rights, erasure protocols, and fiduciary responsibilities.",
      accent: "#fb923c",
      glow: "rgba(251, 146, 60, 0.15)",
      icon: "⚖️",
      count: "🔒 PREMIUM",
      isPremium: true,
      mailtoUrl: `mailto:Salman.Sayyed@onmeridian.com?subject=${encodeURIComponent("Access Request: Premium Module - DPDP Act 2023")}&body=${encodeURIComponent("Hi Salman,\n\nI want to access this premium DPDP Act 2023 auditing module. Please provide me with the details on how to get started.\n\nThanks!")}`
    }
  ];

  return (
    <section className={styles.servicesSection} style={{ background: '#050608' }}>
      <div className="container">
        <div className={styles.servicesHeader}>
          <div>
            <span className={styles.eyebrow}>Supported Compliance Baselines</span>
            <h2 className={styles.servicesTitle}>Framework & Policy Assessments</h2>
          </div>
          <p className={styles.servicesSubtitle} style={{ marginBottom: 0 }}>
            M365 Advisor validates your tenant against the leading cloud security standards and compliance baselines out of the box.
          </p>
        </div>

        <div className={styles.servicesGrid}>
          {assessments.map((item) => {
            const isPremium = item.isPremium;
            const CardTag = isPremium ? "a" : Link;
            const targetUrl = isPremium ? item.mailtoUrl : `/get-started?fw=${item.id}`;
            return (
              <CardTag
                key={item.id}
                className={clsx(styles.serviceCard, isPremium && styles.serviceCardPremium)}
                to={!isPremium ? targetUrl : undefined}
                href={isPremium ? targetUrl : undefined}
                style={{
                  '--card-accent': item.accent,
                  '--card-glow': item.glow,
                  textDecoration: 'none'
                }}
              >
                <div>
                  <div className={styles.cardHeader}>
                    <div className={styles.cardIcon}>{item.icon}</div>
                    <div className={clsx(styles.cardBadge, isPremium && styles.cardBadgePremium)}>{item.count}</div>
                  </div>
                  <h3 className={styles.cardTitle}>{item.title}</h3>
                  <p className={styles.cardSubtitle}>{item.subtitle}</p>
                  <p className={styles.cardDesc}>{item.desc}</p>
                </div>
                <div className={styles.cardFooter}>
                  <span className={styles.cardLearnMore}>{isPremium ? "Request access" : "Explore tests"}</span>
                  <div className={styles.cardArrow}>→</div>
                </div>
              </CardTag>
            );
          })}
        </div>
      </div>
    </section>
  );
}

function BottomNewsletter() {
  return (
    <section className={styles.newsletterSection} style={{ background: '#050608' }}>
      <div className="container" style={{ position: 'relative', zIndex: 1 }}>
        <h2 className={styles.newsletterTitle}>Subscribe to M365 Advisor</h2>
        <p className={styles.newsletterSubtitle} style={{ margin: '0 auto 2.5rem' }}>
          Get the latest security updates, tips, and custom baseline rules directly to your inbox.
        </p>

        <div className={styles.newsletterInputGroup}>
          <input type="email" placeholder="Enter your email" aria-label="Email address" />
          <button className={styles.newsletterButton} type="button">
            Subscribe Now
          </button>
        </div>
      </div>
    </section>
  );
}

export default function Home() {
  const { siteConfig } = useDocusaurusContext();
  return (
    <Layout
      title={siteConfig.title}
      description="M365Advisor is the open source test automation framework for your Microsoft 365 security posture."
      wrapperClassName="home-page"
    >
      <div className={styles.home}>
        <UnifiedHero />
        <OurServices />
        <HowItWorks />
        <BottomNewsletter />
        <div className={styles.footerWatermark} style={{ paddingBottom: '4rem', marginTop: '2rem' }}>
          Secure. Stay Ahead.
        </div>
      </div>
    </Layout>
  );
}
