@echo off

echo ================================================
echo M365 Advisor - Environment & Dependency Diagnostic
echo ================================================
echo.

"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoExit -ExecutionPolicy Bypass -Command "Write-Host '=====================================================' -ForegroundColor Cyan; Write-Host '   M365 Advisor Environment & Dependency Diagnostics' -ForegroundColor Cyan; Write-Host '=====================================================' -ForegroundColor Cyan; Write-Host ''; Write-Host '1. Checking PowerShell Version...' -ForegroundColor Yellow; Write-Host ('   PowerShell ' + $PSVersionTable.PSVersion.ToString() + ' (' + $PSVersionTable.PSEdition + ')') -ForegroundColor Green; Write-Host ''; Write-Host '2. Checking TLS Protocol...' -ForegroundColor Yellow; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls; Write-Host ('   SecurityProtocol: ' + [Net.ServicePointManager]::SecurityProtocol) -ForegroundColor Green; Write-Host ''; Write-Host '3. Checking Pester...' -ForegroundColor Yellow; $pester = Get-Module Pester -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1; if ($pester) { Write-Host ('   Pester Version: ' + $pester.Version) -ForegroundColor Green } else { Write-Host '   Pester is NOT installed.' -ForegroundColor Yellow }; Write-Host ''; Write-Host '4. Checking PnP.PowerShell...' -ForegroundColor Yellow; $pnp = Get-Module PnP.PowerShell -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1; if ($pnp) { Write-Host ('   PnP.PowerShell Version: ' + $pnp.Version) -ForegroundColor Green } else { Write-Host '   PnP.PowerShell is NOT installed.' -ForegroundColor Yellow }; Write-Host ''; Write-Host '5. Checking Audit365 Module...' -ForegroundColor Yellow; $a365 = Get-Module Audit365 -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1; if ($a365) { Write-Host ('   Audit365 Version: ' + $a365.Version + ' at ' + $a365.ModuleBase) -ForegroundColor Green; Import-Module Audit365 -Force; if (Get-Command Connect-M365Advisor -ErrorAction SilentlyContinue) { Write-Host '   Connect-M365Advisor: OK' -ForegroundColor Green } else { Write-Host '   Connect-M365Advisor: NOT FOUND' -ForegroundColor Red }; if (Get-Command Invoke-M365Advisor -ErrorAction SilentlyContinue) { Write-Host '   Invoke-M365Advisor: OK' -ForegroundColor Green } else { Write-Host '   Invoke-M365Advisor: NOT FOUND' -ForegroundColor Red } } else { Write-Host '   Audit365 is NOT installed.' -ForegroundColor Yellow }; Write-Host ''; Write-Host '=====================================================' -ForegroundColor Cyan; Write-Host 'Diagnostics completed.' -ForegroundColor Green; Write-Host '=====================================================' -ForegroundColor Cyan; Read-Host 'Press ENTER to close'"

echo.
echo Diagnostic process ended.
pause