// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: "html",
      value: '<span class="sidebar-section">Get Started</span>'
    },
    "intro",
    "installation",
    {
      type: "category",
      label: "🔗 Connect-M365Advisor",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "connect-M365Advisor" }]
    },
    {
      type: "html",
      value: '<span class="sidebar-section">Use M365Advisor</span>'
    },
    {
      type: "category",
      label: "⚙️ Configure M365Advisor",
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id: 'configuration/overview'},
      items: [{ type: "autogenerated", dirName: "configuration" }]
    },
    "updating-tests",
    "ca-what-if",
    "export-results",
    {
      type: "html",
      value: '<span class="sidebar-section">Automate &amp; Monitor</span>'
    },
    {
      type: "category",
      label: "👁️‍🗨️ Monitoring with M365Advisor",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "monitoring" }]
    },
    {
      type: "category",
      label: "📮 M365Advisor Alerts",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "alerts" }]
    },
    {
      type: "html",
      value: '<span class="sidebar-section">Advanced</span>'
    },
    {
      type: "category",
      label: "🏢 Multi-Tenant",
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id: 'multi-tenant/overview'},
      items: [{ type: "autogenerated", dirName: "multi-tenant" }]
    },
    {
      type: "category",
      label: "🛠️ Writing custom tests",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "writing-tests" }]
    },
    {
      type: "html",
      value: '<span class="sidebar-section">Resources</span>'
    },
    "watch",
    "contributing",
    "faq"
  ],
  testsSidebar: [
    {
      type: "category",
      collapsed: false,
      label: "Tests Overview",
      link: {type: 'doc', id: 'tests/overview'},
      items: [
        "tests/overview",
        {
          type: "category",
          label: "🔥 M365Advisor",
          link: {type: 'doc', id: 'tests/m365advisor/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/m365advisor" }]
        },
        {
          type: "category",
          label: "🛡️ Entra ID SCA",
          link: {type: 'doc', id: 'tests/eidsca/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/eidsca" }]
        },
        {
          type: "category",
          label: "🦅 CISA",
          link: {type: 'doc', id: 'tests/cisa/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/cisa" }]
        },
        {
          type: "category",
          label: "🌀 CIS",
          link: {type: 'doc', id: 'tests/cis/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/cis" }]
        },
        {
          type: "category",
          label: "🐋 ORCA",
          link: {type: 'doc', id: 'tests/orca/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/orca" }]
        },
        "tests/tags/overview"
      ]
    }
  ],
  commandsSidebar: [
    {
      type: "category",
      label: "Command Reference",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "commands" }]
    }
  ]
};

export default sidebars;
